name: dart_plaid
description: A Plaid financial data API library for Dart developers (https://plaid.com)
version: 3.0.0
homepage: https://github.com/point-source/dart_plaid

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  chopper: ^5.1.0
  collection: ^1.15.0
  json_annotation: ^4.4.0
  meta: ^1.7.0

dev_dependencies:
  build_runner: ^2.0.6
  chopper_generator: ^5.1.0+1
  dart_code_metrics: ^5.0.1
  json_serializable: ^6.1.3
  lints: ^2.0.1
  swagger_dart_code_generator: ^2.3.13
  test: ^1.20.1

dependency_overrides:
  swagger_dart_code_generator:
    git:
      url: https://github.com/epam-cross-platform-lab/swagger-dart-code-generator