name: dart_plaid
description: A Plaid financial data API library for Dart developers (https://plaid.com)
version: 1.0.0
homepage: https://github.com/point-source/dart_plaid

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  chopper: ^4.0.1
  collection: ^1.15.0
  json_annotation: ^4.1.0
  meta: ^1.7.0

dev_dependencies:
  build_runner: ^2.0.6
  chopper_generator: ^4.0.1
  dart_code_metrics: ^4.1.0
  json_serializable: ^4.1.3
  lints: ^1.0.1
  swagger_dart_code_generator: ^2.0.8+1
  test: ^1.16.0
